import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { format } from 'prettier';
import {
  M68000_ISA_MANIFEST,
  summarizeIsaCoverage,
  validateIsaManifest,
} from '../packages/interpreter/src/isa/manifest';

const issues = validateIsaManifest();
if (issues.length > 0) {
  throw new Error(
    `Cannot generate ISA report from an invalid manifest:\n${issues
      .map((issue) => `${issue.formId}: ${issue.message}`)
      .join('\n')}`
  );
}

const summary = summarizeIsaCoverage();
const outputPath = resolve('docs/generated/M68000_ISA_COVERAGE.md');
mkdirSync(resolve('docs/generated'), { recursive: true });

const rows = [...M68000_ISA_MANIFEST]
  .sort(
    (left, right) =>
      left.minimumProfile.localeCompare(right.minimumProfile) ||
      left.mnemonic.localeCompare(right.mnemonic) ||
      left.id.localeCompare(right.id)
  )
  .map(
    (instruction) =>
      `| \`${instruction.id}\` | ${instruction.minimumProfile} | ${instruction.sizes.join(
        ', '
      )} | ${instruction.support} |`
  );

const report = `# Generated M68000 ISA Coverage

Generated by \`yarn generate:isa-report\`. Do not edit this file by hand.

## Summary

| Metric | Count |
| --- | ---: |
| Total instruction forms | ${summary.totalForms} |
| Unique mnemonics | ${summary.uniqueMnemonics} |
| Strict MC68000 forms | ${summary.byProfile.m68000} |
| MC68010 extension forms | ${summary.byProfile.m68010} |
| Easy68K compatibility forms | ${summary.byProfile.easy68k} |
| Legacy runtime only | ${summary.bySupport['legacy-only']} |
| Strict core, partial | ${summary.bySupport['strict-core-partial']} |
| Integrated, audit required | ${summary.bySupport['integrated-needs-audit']} |
| Conformant | ${summary.bySupport.conformant} |
| Missing | ${summary.bySupport.missing} |
| Extension only | ${summary.bySupport['extension-only']} |
| Compatibility only | ${summary.bySupport['compatibility-only']} |

## Forms

| Form | Minimum profile | Sizes | Support |
| --- | --- | --- | --- |
${rows.join('\n')}
`;

async function main(): Promise<void> {
  writeFileSync(outputPath, await format(report, { parser: 'markdown' }));
}

void main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
