import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { format } from 'prettier';
import {
  M68000_ISA_MANIFEST,
  MACHINE_COMPATIBILITY_EVIDENCE,
  summarizeIsaCoverage,
  validateIsaManifest,
} from '../packages/interpreter/src/isa/manifest';
import {
  MC68010_ARCHITECTURAL_DIFFERENCES,
  MC68010_DEFERRED_PHYSICAL_BUS_SCOPE,
  MC68010_INSTRUCTION_INVENTORY,
} from '../packages/interpreter/src/isa/mc68010Inventory';
import { MC68020_EXTENSION_LEGALITY } from '../packages/interpreter/src/isa/mc68020Inventory';

const issues = validateIsaManifest();
if (issues.length > 0) {
  throw new Error(
    `Cannot generate ISA report from an invalid manifest:\n${issues
      .map((issue) => `${issue.formId}: ${issue.message}`)
      .join('\n')}`
  );
}

const summary = summarizeIsaCoverage();
const outputPath = resolve('docs/generated/M68000_ISA_COVERAGE.md');
const mc68010OutputPath = resolve('docs/generated/MC68010_FUNCTIONAL_INVENTORY.md');
const mc68020OutputPath = resolve('docs/generated/MC68020_FUNCTIONAL_INVENTORY.md');
mkdirSync(resolve('docs/generated'), { recursive: true });

const rows = [...M68000_ISA_MANIFEST]
  .sort(
    (left, right) =>
      left.minimumCpuModel.localeCompare(right.minimumCpuModel) ||
      left.mnemonic.localeCompare(right.mnemonic) ||
      left.id.localeCompare(right.id)
  )
  .map((instruction) => {
    const pipelineEvidence =
      instruction.support === 'conformant'
        ? 'source encoder; binary decoder; strict executor'
        : instruction.support === 'extension-only'
          ? 'source encoder; profile-gated decoder; strict executor'
          : 'profile-gated decoder and executor';
    const testEvidence =
      instruction.support === 'conformant'
        ? instruction.minimumCpuModel === 'm68020'
          ? 'deterministic CPU; extension legality; all-opcode classifier; selected Musashi/Moira samples'
          : 'deterministic CPU; all-opcode classifier; MAME corpus; Musashi/Moira sample'
        : instruction.support === 'extension-only'
          ? 'deterministic CPU; EA matrix; all-opcode classifier; Musashi/Moira MC68010'
          : 'profile legality and execution tests';
    return `| \`${instruction.id}\` | ${instruction.minimumCpuModel} | ${instruction.sizes.join(
      ', '
    )} | ${instruction.support} | ${pipelineEvidence} | ${testEvidence} |`;
  });

const report = `# Generated M68000 Family ISA Coverage

Generated by \`yarn generate:isa-report\`. Do not edit this file by hand.

## Summary

| Metric | Count |
| --- | ---: |
| Total instruction forms | ${summary.totalForms} |
| Unique mnemonics | ${summary.uniqueMnemonics} |
| Strict MC68000 forms | ${summary.byCpuModel.m68000} |
| MC68010-specific forms | ${summary.byCpuModel.m68010} |
| MC68020-specific forms | ${summary.byCpuModel.m68020} |
| Easy68K compatibility evidence | ${summary.machineCompatibility.easy68k} |
| Legacy runtime only | ${summary.bySupport['legacy-only']} |
| Strict core, partial | ${summary.bySupport['strict-core-partial']} |
| Integrated, audit required | ${summary.bySupport['integrated-needs-audit']} |
| Conformant | ${summary.bySupport.conformant} |
| Missing | ${summary.bySupport.missing} |
| Extension only | ${summary.bySupport['extension-only']} |
| Compatibility only | ${summary.bySupport['compatibility-only']} |

## Machine compatibility evidence

| Evidence | Machine | Capability | Support |
| --- | --- | --- | --- |
${MACHINE_COMPATIBILITY_EVIDENCE.map(
  (evidence) =>
    `| \`${evidence.id}\` | ${evidence.machineProfile} | ${evidence.capability} | ${evidence.support} |`
).join('\n')}

## Evidence and audit policy

\`conformant\` means the form is represented by the source/binary pipeline and
the authoritative strict core, with deterministic profile-specific evidence.
The MC68000 denominator additionally uses the complete 65,536-word classifier
and pinned MAME family corpus. Run
\`yarn test:oracles\` for bounded Musashi/Moira differentials and
\`yarn test:oracles:mame\` for all 317,500 MAME vectors.

The full MAME audit fails on unexplained differences. Its generated JSON keeps
the reviewed temporal quarantines separate from exact matches: MC68000 internal
address-error frames/bus sequencing, prefetch-stage fault attribution, and
undefined CHK condition bits saved in an exception frame.

## Forms

| Form | Minimum CPU model | Sizes | Support | Pipeline evidence | Test evidence |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}
`;

const mc68010Report = `# Generated MC68010 Functional Inventory

Generated by \`yarn generate:isa-report\`. Do not edit this file by hand.

Primary specification: Motorola/NXP M68000 Family Programmer's Reference Manual
and M68000 8-/16-/32-bit Microprocessors User's Manual.

## Instruction denominator

| Form | Encoding | Extension words | Sizes | Operands | Privileged | Flags | Exceptions | Bus effect |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${MC68010_INSTRUCTION_INVENTORY.map(
  (entry) =>
    `| \`${entry.id}\` | ${entry.encoding} | ${entry.extension} | ${entry.sizes} | ${entry.operands} | ${entry.privileged ? 'yes' : 'no'} | ${entry.flags} | ${entry.exceptions} | ${entry.busEffect} |`
).join('\n')}

## Architectural differences from MC68000

| Area | MC68010 contract |
| --- | --- |
${MC68010_ARCHITECTURAL_DIFFERENCES.map(([area, contract]) => `| ${area} | ${contract} |`).join('\n')}

## Explicit physical-bus deferrals

${MC68010_DEFERRED_PHYSICAL_BUS_SCOPE.map((item) => `- ${item}`).join('\n')}

These deferrals do not change programmer-visible instruction, state, exception,
or successful restart behavior.
`;

const mc68020Forms = M68000_ISA_MANIFEST.filter((entry) => entry.minimumCpuModel === 'm68020');
const mc68020Report = `# Generated MC68020 Functional Inventory

Generated by \`yarn generate:isa-report\`. Do not edit this file by hand.

Primary specification: Motorola/NXP M68000 Family Programmer's Reference Manual
and MC68020 32-Bit Microprocessor User's Manual.

## Coverage summary

| Metric | Count |
| --- | ---: |
| MC68020-specific instruction forms | ${mc68020Forms.length} |
| Missing forms | ${mc68020Forms.filter((entry) => entry.support === 'missing').length} |
| Audit-pending forms | ${mc68020Forms.filter((entry) => entry.support === 'integrated-needs-audit').length} |
| Effective-address categories | 18 |
| Logical address bits | 32 |

The integer profile is functional rather than cycle- or pin-accurate. External
MC68881/MC68882 floating-point arithmetic and MC68851 page-table semantics are
not included; their attachment and translation contracts are tested separately.

## Instruction denominator

| Form | Sizes | Support | Encoding |
| --- | --- | --- | --- |
${mc68020Forms.map((entry) => `| \`${entry.id}\` | ${entry.sizes.join(', ')} | ${entry.support} | ${entry.encoding ? `\`${entry.encoding.value.toString(16).padStart(4, '0')}/${entry.encoding.mask.toString(16).padStart(4, '0')}\`` : 'inherited family encoding'} |`).join('\n')}

## Extension-word legality

| Family | Reserved-bit mask/value | Contract |
| --- | --- | --- |
${MC68020_EXTENSION_LEGALITY.map((rule) => `| ${rule.family} | \`${rule.mask.toString(16).padStart(4, '0')}/${rule.value.toString(16).padStart(4, '0')}\` | ${rule.notes} |`).join('\n')}
`;

async function main(): Promise<void> {
  writeFileSync(outputPath, await format(report, { parser: 'markdown' }));
  writeFileSync(mc68010OutputPath, await format(mc68010Report, { parser: 'markdown' }));
  writeFileSync(mc68020OutputPath, await format(mc68020Report, { parser: 'markdown' }));
}

void main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
